smtp_on: true
smtp_host: smtp.gmail.com
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_username: raveenamathur91@gmail.com
smtp_password: bohotparamummypapa26952496
smtp_from: raveenamathur91@gmail.com
smtp_fromname: 'Raveena Mathur'
smtp_allowhtml: '0'
smtp_test_address: ''
smtp_debugging: true
prev_mail_system: php_mail
_core:
  default_config_hash: U7C23Wy4M4Eq8X8ExjU4n3yq7PtfU1S-jebw2hikU5g
